### ISSUE TITLE
Installation: pg_config considerations

### ISSUE THREAD

**Issue by MichaelDBA** [aws/pg_tle#159]
The installation instructions do not explicitly talk about the PG instance context: **pg_config**.  It will not work for PG versions less than 14.  Only 14 and 15 at the present time (by design I reckon).
Add another instruction to the installation step saying to set the PG context BEFORE doing the make:
`which pg_config`
`export PATH=/usr/pgsql-14/bin/:$PATH` (CentOS distro context)
`which pg_config`

**Comment by jkatz** [comment]
@MichaelDBA I tested this against the PostgreSQL 13 development files available on Ubuntu and was not able to reproduce the issue (i.e. `pg_config` is in the path). This may be platform dependent.

That said, we could do a few things:

1. Modify the `Makefile` to let `PG_CONFIG` be set by the user.
2. Update the documentation to specify that either `pg_config` must in the `PATH` or that one can set the `PG_CONFIG` Makefile variable.
