### ISSUE TITLE
PG 15: cannot load pg_tle on startup

### ISSUE THREAD

**Issue by MichaelDBA** [aws/pg_tle#164]
I get this error when I try to start PG 15 after updating shared_preload_libraries with pg_tle:
`FATAL:  could not load library "/usr/pgsql-15/lib/pg_tle.so": /usr/pgsql-15/lib/pg_tle.so: undefined symbol: pg_analyze_and_rewrite`

Linux Distro: CentOS Stream release 8

It works fine when doing the make and install for PG14.

**Comment by davecramer** [comment]
Did you build this from source ? There is a macro to change the name if it is being build using PG15

**Comment by davecramer** [comment]
Did you build this using PG15 binaries ?

**Comment by MichaelDBA** [comment]
Yes, did the git download and the make, make install after setting the path to point to the pg_config for PG 15.
Yes, also to using the PGDG binaries.

But I didnt see anything about changing the name macro?  Can you fill me in on that part?

**Comment by davecramer** [comment]
You should not have to do anything as long as you build it using PG15

> Ahh, Dave! so you are involved with this beautiful bad boy!

a little.

**Comment by MichaelDBA** [comment]
so i have it compiled for PG14 and PG15 on the same host.  So how do i fix it for PG15?

**Comment by davecramer** [comment]
When I have done it on the same host, I need to compile both PG14 and PG15 and install both in separate directories. After that you need to make sure that you point to the correct pg_config. @jkatz has just merged in a fix to allow you to set PG_CONFIG as an environment variable see https://github.com/aws/pg_tle/blob/33fc15a249ace0d935b7e142d10e728d3a69cc96/Makefile#L21. I just change the path before `make`

**Comment by MichaelDBA** [comment]
That worked for me as well, closing this issue, Thanks!
