### ISSUE TITLE
Make it work for all current, non-EOL versions of PG

### ISSUE THREAD

**Issue by MichaelDBA** [aws/pg_tle#169]
Currently, this wonderful tool works for PG12 and up.  Would it be too much work to make it work for the other non-EOL version, PG v11?

**Comment by jkatz** [comment]
#166 and #167 added compatibility with v13 and v12 respectively. Are there any other versions you are looking for?

**Comment by jkatz** [comment]
@MichaelDBA Is there a specific reason why you are looking for v11 support? v11 is going to be EOL in Nov 2023 and I'd be curious to understand the use case around supporting `pg_tle` for v11 particularly for new development.

**Comment by jkatz** [comment]
@MichaelDBA Thanks for the info. #170 adds compatibility with v11.

If you're willing to share, I'd love to learn more about your use-cases to understand what we can to do continue to improve `pg_tle`.

**Comment by MichaelDBA** [comment]
One major thing I noticed is that the body of the pgtle.install_extension API is not compiled for syntax.  You need to test your funcs, types, etc outside the body of the install extension for compile errors.  Would it be too hard to do that?

**Comment by MichaelDBA** [comment]
One thing I have done with this extension is write wrappers (views) around metadata queries to assist newbies to the PG world.  Also providing common functionality not available in PG:
* change owner for all objects in a schema
* clone a schema
* get table ddl, interesting how there are a lot of functions like getViewDef, etc., but none for tables

**Comment by jconway** [comment]
> One major thing I noticed is that the body of the pgtle.install_extension API is not compiled for syntax. You need to test your funcs, types, etc outside the body of the install extension for compile errors. Would it be too hard to do that?

On one hand, that is no different than when you develop a normal/file-based extension. On the other, it sounds useful.

Maybe something like "BEGIN; CREATE EXTENSION <extname>; ABORT" (programmatically as part of pgtle.install_extension) could be used to proactively catch extension script errors somehow?

Seems like a bit of a hack though...
