### ISSUE TITLE
uninstall_extension returns error if extension does not exist

### ISSUE THREAD

**Issue by MichaelDBA** [aws/pg_tle#173]
## Describe the problem
-- The following call returns an error (code exception raised) if the pgtle extension does not exist.
SELECT pgtle.uninstall_extension('myutils');

* What are you trying to solve?
I would like to proceed to other statements upon encountering this error.

## Describe the proposal
Have the uninstall_function raise a WARNING, not EXCEPTION, and return false instead of true from the function.
Then it would act like a regular PG object with a IF EXISTS parameter feature.

* What is the feature you are proposing?
* How would it solve the problem?
I would like to proceed to other statements and not have to comment out this function to be able to proceed again.
I

## Describe alternatives
Just comment out the call to the uninstall_extension if I know it's not installed.

* How would you solve the problem today if the feature is not built?
Just comment out the call and try again.

**Comment by jkatz** [comment]
@MichaelDBA Does [`pgtle.uninstall_extension_if_exists`](https://github.com/aws/pg_tle/blob/main/docs/03_managing_extensions.md#pgtleuninstall_extension_if_existsextname-text) solve this problem? This function already exists.

**Comment by MichaelDBA** [comment]
No freakin way! Ha!
