### ISSUE TITLE
CLI - Request for Comments

### ISSUE THREAD

**Issue by olirice** [aws/pg_tle#180]
# Purpose

Provide tooling for creating, publishing, and installing TLEs.

As an end user, I want to:
- install extensions from a package index into a database
- uninstall extensions from a database (by name)

As a package author, I want to:
- install extensions from a local directory into a database
- sign up for an account with a package index
- publish extensions to a package index

Note:
- This RFC is for the CLI interface only. Specifics of the package index implementation, web interface, etc, are out of scope.
- Design is intentionally minimal. Significantly more configurability will be required for e.g. installing a specific version

# Proposal

```help
Usage: tle [OPTIONS] <COMMAND>

Commands:
  install    Install a package to a database
  uninstall  Uninstall a package from a database
  signup    Create a user account
  publish    Upload a package to the package index
  help       Print this message or the help of the given subcommand(s)

Options:
  -d, --debug    Turn debugging information on
  -h, --help     Print help
  -V, --version  Print version
```

### install

```
Install a package to a database

Usage: tle install [OPTIONS] --connection <CONNECTION>

Options:
  -c, --connection <CONNECTION>  PostgreSQL connection string
  -p, --package <PACKAGE>        Package name on package index
      --path <PATH>              From local directory
  -h, --help                     Print help
```

### uninstall

```
Uninstall a package from a database

Usage: tle uninstall --connection <CONNECTION> --package <PACKAGE>

Options:
  -c, --connection <CONNECTION>  PostgreSQL connection string
  -p, --package <PACKAGE>        Package name on database.new in form handle/package
  -h, --help                     Print help
```

### sign-up

```
Create a user account

Usage: tle sign-up <HANDLE>

Arguments:
  <HANDLE>  PostgreSQL connection string

Options:
  -h, --help  Print help
```

The user is additionally prompted for an email address and password during sign-up. Packages can not be uploaded to an account until the email address is confirmed.

### publish

```
Upload a package to the package index

Usage: tle publish

Options:
  -h, --help  Print help
```

Publishes the current directory's TLE package to the package index.

**Comment by kiwicopple** [comment]
>   sign-up    Create a user account

Perhaps we need a way to login as well (existing user). Also a nit - could be cleaner without hyphens:

```
Commands:
  login    Log into existing user account
  logout  Log out of the registry
  signup    Create a new user account
```

**Comment by jim-mlodgenski** [comment]
> The user is additionally prompted for an email address and password

I think we need to think through the server side implementation before we get into what the UI is from the CLI. What is the user signing up for and where is the email address stored? That is PII so as an open source project collecting any sort of user data would be outside out charter.

**Comment by olirice** [comment]
> Perhaps we need a way to login as well (existing user). 

I was thinking that, similar to pip, there would be an (optional) configuration file at `~/.tlerc` that could store credentials so they wouldn't need to be typed in every time
```toml
[tle]
username = 
password = 
```

if that file is not present, the user is prompted for a username/password on `publish`

> Also a nit - could be cleaner without hyphens:

updated

**Comment by olirice** [comment]
> What is the user signing up for and where is the email address stored?

The user would only be signing up for an account on the index so they could publish and manage their own packages. Looking forward, it would also be useful to have a method to contact package developers if
e.g.:
- they lose their credentials and need to recover
- they push a package that isn't installable
- one of their package's dependencies has a security update

> That is PII so as an open source project collecting any sort of user data would be outside out charter

Did you have something else in mind to allow users to authenticate themselves while publishing packages or is anything that allows authentication a problem?

**Comment by jim-mlodgenski** [comment]
" The user would only be signing up for an account on the index"

What is the index? It sounds like this is a CLI for a public repository of
extensions. What does that look like? Who runs it? How are things published
to it verified to not do anything nefarious on users databases? I think we
need to understand what the "index" is in detail before designing a CLI to
it.

**Comment by olirice** [comment]
@jim-mlodgenski some additional context:

This RFC came out of last Wednesday's discussion between Supabase, Jonathan Katz, John Dalton, and Jignesh Shah.

[supabase](https://supabase.com) is adopting `pg_tle` and we're interested in helping with the developer experience. The minimal option would be to create a CLI with an `install` and `uninstall` command similar to [`pg_tle_manage_local_extension`](https://github.com/aws/pg_tle/tree/main/tools/pg_tle_manage_local_extension) written in a more easily deployable language so it can be installed via brew/apt/whatever.

We also talked about the possibility of a CLI for a full package index experience (pip/cargo) in combination with an update to `pg_tle` that would allow installing extensions directly from that index. The most significant benefits from that would be:
- no CLI would be required for end users to install extensions
- extension setup can be contained in SQL migrations

for example:
```sql
select tle.install_extension('pgjwt');
-- checks the package index to see if a pgjwt extension exists
-- if so, downloads and installs it
create extension pgjwt;
```

instead of
```sh
git clone git@github.com:michelp/pgjwt.git
git clone git@github.com:aws/pg_tle.git
cd pg_tle/tools/pg_tle_manage_local_extension
./pg_tle_manage_local_extension.sh -a install -c '<connection_string>' -n pgjwt -p ../../pgjwt
```
and then
```sql
select tle.install_extension('pgjwt');
create extension pgjwt;
```

The specifics of how the package would be fetched are TBD (probably the `aws_lambda` extension). @michelp will be opening a separate RFC for the in-database installer side of the convo.

Nothing has been decided on yet. This thread is intended to figure out how much overlap we have wrt goals and what the ideal developer experience would be for package publishers.

---

> What is the index? It sounds like this is a CLI for a public repository of
extensions. 

Correct

> What does that look like? Who runs it?

I think we'd have `pg_tle` define an expected API for package indexes and allow users to add their own index URLs. That would open it up for any interested party to create/manage an index and allow `pg_tle` to remain narrowly scoped on security.

**Comment by jim-mlodgenski** [comment]
I think those are worthwhile goals, but it's probably best to break things
apart into smaller chunks so they can be discussed and designed on their
own merits.

Maybe we just start with this:
"The minimal option would be to create a CLI with an install and uninstall
command similar to pg_tle_manage_local_extension
<https://github.com/aws/pg_tle/tree/main/tools/pg_tle_manage_local_extension>
written in a more easily deployable language so it can be installed via
brew/apt/whatever."

**Comment by olirice** [comment]
thanks

closing for now until we have a better understanding of scope boundaries between `pg_tle` and a (potential) package index
