### ISSUE TITLE
TLE installation does automatically update to the default version like Postgres extensions do

### ISSUE THREAD

**Issue by michelp** [aws/pg_tle#181]
## Description

If a Postgres extension provides `foo--1.0.sql`, `foo--1.0--1.1.sql` and `foo.control` where `default_version = 1.1` then Postgres 10+ will install both scripts and follow the shortest upgrade path to update the extension to 1.1 when you run `CREATE EXTENSION foo`.

TLEs do not follow this same pattern, you must install a `foo--1.1.sql` if the default version is `1.1`.  This is the behavior of postgres prior to version 10.  For postgres 10+, the database automatically updates extensions avoiding the need for mostly duplicate files.  This prevents many existing modern extensions written in trusted languages from being usable as TLEs without adding a "dummy" duplicate version file as done here in [pgjwt](https://github.com/michelp/pgjwt/commit/b38207f3c95ac475ab89686ed9b2494428d50a4f).

## Expected outcome

As noted in [Postgres' extension packaging documentation](https://www.postgresql.org/docs/current/extend-extensions.html#id-1.8.3.20.15)

> An extension that has been around for awhile will probably exist in several versions, for which the author will need to write update scripts. For example, if you have released a foo extension in versions 1.0, 1.1, and 1.2, there should be update scripts foo--1.0--1.1.sql and foo--1.1--1.2.sql. Before PostgreSQL 10, it was necessary to also create new script files foo--1.1.sql and foo--1.2.sql that directly build the newer extension versions, or else the newer versions could not be installed directly, only by installing 1.0 and then updating. That was tedious and duplicative, but now it's unnecessary, because CREATE EXTENSION can follow update chains automatically. For example, if only the script files foo--1.0.sql, foo--1.0--1.1.sql, and foo--1.1--1.2.sql are available then a request to install version 1.2 is honored by running those three scripts in sequence. The processing is the same as if you'd first installed 1.0 and then updated to 1.2. (As with ALTER EXTENSION UPDATE, if multiple pathways are available then the shortest is preferred.) Arranging an extension's script files in this style can reduce the amount of maintenance effort needed to produce small updates.

**Comment by michelp** [comment]
Here's a snippet to reproduce the problem:

**Comment by michelp** [comment]
Here's a snippet that reproduces the issue:
```

SELECT pgtle.install_extension('foo', '0.1', 'comment',
$_pg_tle_$
    CREATE FUNCTION bar()
    RETURNS bool
    AS $$
      BEGIN
		RETURN true;
      END
    $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;
$_pg_tle_$
);

SELECT pgtle.install_update_path('foo', '0.1', '0.2',
$_pg_tle_$
    CREATE OR REPLACE FUNCTION bar()
    RETURNS bool
    AS $$
      BEGIN
		RETURN false;
      END
    $$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;
$_pg_tle_$
);

select pgtle.set_default_version('foo', '0.2');

CREATE EXTENSION foo;

DROP EXTENSION foo;

SELECT pgtle.uninstall_extension('foo');
```
This returns:
```

postgres=# \i pg_tle/repr_bug.sql
 install_extension 
-------------------
 t
(1 row)

 install_update_path 
---------------------
 t
(1 row)

 set_default_version 
---------------------
 t
(1 row)

psql:pg_tle/repr_bug.sql:36: ERROR:  could not find sql function "foo--0.2.sql" for extension foo in schema pgtle
postgres=# 
```

But `set_default_version` should detect there is a path to 2.0 and not error out, and `CREATE EXTENSION` will follow that path to install the default version.

**Comment by olirice** [comment]
any update available on this one?

the interest in getting this ironed out is that stateful extensions can't be upgraded by drop/create without losing user data

**Comment by adamguo0** [comment]
Thanks for reporting this issue, we are actively working on resolving it.

**Comment by olirice** [comment]
During our testing before rollout of #209 we ran into an issue:

specifying the version to install during the `create extension` statement causes a segfault
```sql
create extension pg_tle;

select pgtle.install_extension('foo', '0.1', 'comment', $$ select 1 $$);
select pgtle.install_update_path('foo', '0.1', '0.2', $$ select 1 $$);

create extension foo version '0.2';
```

Logs
```
2023-07-10 17:21:18.441 CDT [54373] LOG:  server process (PID 54485) was terminated by signal 11: Segmentation fault: 11
2023-07-10 17:21:18.441 CDT [54373] DETAIL:  Failed process was running: create extension foo version '0.2';
2023-07-10 17:21:18.441 CDT [54373] LOG:  terminating any other active server processes
2023-07-10 17:21:18.443 CDT [54373] LOG:  all server processes terminated; reinitializing
2023-07-10 17:21:18.451 CDT [54490] LOG:  database system was interrupted; last known up at 2023-07-10 17:20:51 CDT
2023-07-10 17:21:18.509 CDT [54490] LOG:  database system was not properly shut down; automatic recovery in progress
2023-07-10 17:21:18.510 CDT [54490] LOG:  redo starts at 0/2EE9010
2023-07-10 17:21:18.518 CDT [54490] LOG:  invalid record length at 0/2F530B8: wanted 24, got 0
2023-07-10 17:21:18.518 CDT [54490] LOG:  redo done at 0/2F53050 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2023-07-10 17:21:18.520 CDT [54491] LOG:  checkpoint starting: end-of-recovery immediate wait
2023-07-10 17:21:18.523 CDT [54491] LOG:  checkpoint complete: wrote 84 buffers (0.5%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.002 s, total=0.004 s; sync files=53, longest=0.001 s, average=0.001 s; distance=424 kB, estimate=424 kB
2023-07-10 17:21:18.524 CDT [54373] LOG:  database system is ready to accept connections
```

note that if you `pgtle.set_default_version` to the preferred version it works as expected and does follow upgrade paths

**Comment by adamguo0** [comment]
Ah thanks for bringing that up. Working on a small fix for this segfault
