### ISSUE TITLE
Multiple versions of the same extension

### ISSUE THREAD

**Issue by olirice** [aws/pg_tle#186]
## Description
Currently it is not possible to load multiple full install scripts of the same extension. For example `0.1.0` and `0.2.0`. That behavior is inconsistent with Postgres native extensions. 

Repro Case:
```sql
select 
	pgtle.install_extension(
		'olirice-example',
		'0.1.0',
		'Issue example',
		$$ create function add (int, int) returns int as $f$ select $1 + $2; end$f$ $$
	);
	
select 
	pgtle.install_extension(
		'olirice-example',
		'0.2.0',
		'Issue example',
		$$ create function add (int, int) returns int as $f$ select $1 + $2; end$f$ $$
	);
```
Error:
``` 
ERROR:  extension "olirice-example" already installed
SQL state: 42710
```

## Goal
Multiple versions of the same extension can be installed so installing can go straight to requested version rather than following the upgrade paths (if available)

**Comment by formalLogicGirl** [comment]
I'm proposing fixing this to allow a secondary extension control file, which may set the same parameters as the primary control file except default_version. Also proposing adding a parameter -- ctl_secondary or ctl_alt or other such name, suggestions welcome -- to the install_extension interface to allow specifying that this is a secondary control file.

PostgreSQL native extension secondary control file behavior
"n addition to the primary control file extension.control, an extension can have secondary control files named in the style extension--version.control. If supplied, these must be located in the script file directory. Secondary control files follow the same format as the primary control file. Any parameters set in a secondary control file override the primary control file when installing or updating to that version of the extension. However, the parameters directory and default_version cannot be set in a secondary control file."
from https://www.postgresql.org/docs/current/extend-extensions.html

**Comment by olirice** [comment]
> allow a secondary extension control file

@formalLogicGirl I'm not sure I totally follow the relationship between secondary control files, default versions, and the `pgtle.install_extension` interface as it relates to allowing multiple install versions.

It is valid for an extension to provide multiple versions e.g.
```
extension--0.1.0.sql
extension--0.2.0.sql
extension--0.3.0.sql
```
as well as upgrade pathes
```
extension--0.1.0--0.2.0.sql
extension--0.2.0--0.3.0.sql
```
while the control file may specify a default of any of the available versions
```
# extension.control
default_version = 0.2.0
```

I didn't have secondary control files in mind when opening the issue, only the ability to pre-load multiple full install files (`extension--0.1.0.sql` + `extension--0.2.0.sql`) at the same time so users can manually specify which version they'd like to create.

```
create extension "extension" version '0.1.0';
-- OR
create extension "extension" version '0.2.0';
```
without forcing postgres to process all the upgrade scripts to get to the target version.

----

Last week @jkatz mentioned that restricting full install scripts to exactly 1 version was an intentional design decision that is known to be more strict the default PostgreSQL.

The advantage being that it removes the possibility of drift between users who follow the upgrade path and users who do a fresh install of the latest version.

After thinking on it, I'm on board with that additional strictness, but would like to clarify that everyone is on the same page about it / it is not going to change. 

For context, I'm interested in getting that clarification early because its a requirement that we'll have to push on users of [dbdev](https://github.com/supabase/dbdev) and we'll want to enforce it on-package-publish

thanks!

**Comment by formalLogicGirl** [comment]
I was interpreting your request to be asking to allow alternate versioned control files like PostgreSQL does. But I see now that you were asking about multiple versioned .sql files only.

For some more context, if we are actually considering multiple versions of an extension's .sql file, my understanding of PostgreSQL extensions is that there can be multiple versions of .sql files installed on the server. But only one version at a time can be created in a database. With pg_tle, the extension is installed only in a database, there is no server level install.

Reading the further note after jkatz's clarification, are you still asking about having multiple versions of .sql files installed in a single database? Or are we ok with only one version installed in the database at a time? With the current design, creating a different version requires either uninstalling the old version and installing the new version, or following an upgrade path.

**Comment by formalLogicGirl** [comment]
We can fix this to allow installing multiple versions in the same database, just need to either change the install_extension API to allow version number, or add a new function -- like install_extension_version -- that allows installing the versioned sql file independently of the ctl file. Is there a preference for one of those?

Also need to make corresponding updates on uninstall_extension. Whether uninstall should take a version number (to uninstall a specific version and not all versions) or a new function to uninstall only a versioned sql file.

I think I like the approach of updating the existing functions and not adding the new functions to install/uninstall only a versioned sql file. Helps to cleanly manage cleanup of the ctl file and sql files, without ever leaving a zombie ctl file with no sql files, or have only a sql file with no ctl file.

**Comment by formalLogicGirl** [comment]
yes, and we can add a flag in install_extension to specify if its a sql file only install, such as when there is already a control file and a different version that has been installed.

So the change would look like this
pgtle.install_extension
(
  name text,
  version text,
  description text,
  ext text,
  requires text[] DEFAULT NULL,
  sql_only bool default false
)

The sql_only flag can be set to true to specify its another version being installed. And there is a check for existence of the control file in that case, and the install fails if there is no control file.

**Comment by formalLogicGirl** [comment]
And for uninstall_extension, we'd keep the same signature as now.
pgtle.uninstall_extension
(
name text,
version text
}
If the version specified is the default_version, then the entire extension i.e., all versions get uninstalled. Otherwise, only the specified version is uninstalled.

**Comment by olirice** [comment]
> If the version specified is the default_version, then the entire extension i.e., all versions get uninstalled. Otherwise, only the specified version is uninstalled.

I think it might be safer if attempting to uninstall the `default_version` raises an error with a hint to use `pgtle.set_default_version` to change the default. Otherwise, the user could be surprised that the delete cascades to all versions.

**Comment by formalLogicGirl** [comment]
yes, good point about the accidental uninstall of everything, should have a safeguard to prevent that, and what you propose would do that. We'd need some way to specify uninstall everything at once too, so maybe a new function signature that doesn't specify any version? Maybe the error signature you propose says to change the default or use this other function without a version?

**Comment by olirice** [comment]
For the 3 `uninstall_extension` functions, the behavior that I'd expect to be intuitive to users is:

### pgtle.uninstall_extension(extname text)
1. If extension exists -> uninstall all versions and control file

2. If extension does not exist -> error

### pgtle.uninstall_extension_if_exists(extname text)
1. If extension exists -> uninstall all versions and control file

2. If extension does not exist -> do nothing

### pgtle.uninstall_extension(extname text, version text)
1. If extension + version does not exist -> error

2. If extension + version exists and is not the `default_version` -> uninstall extension/version combination

3. If extension + version exists and is the `default_version` and other versions exist -> error and hint to use 
`set_default_version` to update the default to another available version before retrying

4. If extension + version exists and is the `default_version` and no other versions exist -> uninstall the extension and control file

**Comment by formalLogicGirl** [comment]
Which makes a better user experience?

Having only one function, and sql_only is a required parameter
pgtle.install_extension
(
name text,
version text,
description text,
ext text,
sql_only bool,
requires text[] default NULL
)

OR
having 2 different functions
One the same as it is now
pgtle.install_extension
(
name text,
version text,
description text,
ext text,
requires text[] default NULL
)

Another that takes a sql_only parameter which is required 
pgtle.install_extension_version
(
name text,
version text,
description text,
ext text,
sql_only bool,
requires text[] default NULL
)

Since 'requires' is already an optional parameter, I'd have to change that in the API to add sql_only as an optional parameter. But we don't want to do that.

I thought the second way with two functions might be better if the majority of install_extension calls don't want a sql_only install. Although the hassle of having to always add an extra true/false parameter may be not so terrible. What do you think?

**Comment by formalLogicGirl** [comment]
From a user experience perspective, doing

pgtle.install_extension
(
name text,
version text,
description text,
ext text,
requires text[] default NULL,
sql_only bool default false
)

means having to explicitly specify the default for 'requires' (where no non-default values were used before) in order to specify sql-only = true. Is that going to be a hassle?

The alternative is to not change the existing function and add a new function
pgtle.install_extension_sql_only
(
name text,
version text,
description text,
ext text,
sql_only bool default false,
requires text[] default NULL
)

What would you prefer? @olirice

**Comment by formalLogicGirl** [comment]
Actually, from a design perspective, the new function seems better to me than adding a sql_only parameter to pgtle.install_function. Because in the sql_only case, we also have to disallow some of the required parameters for pgtle.install_function like description and requires. So I'm going with that. Will start a PR with that.

**Comment by olirice** [comment]
> the new function seems better to me than adding a sql_only parameter to pgtle.install_extension

Agreed

imo a good option would be to map the functions to the components of the underlying extension system

A function for registering a control file:
```sql
pgtle.install_extension(
  name text,
  default_version text,
  description text,
  requires text[]
  -- note, does not include default version
)
```

a function registering complete versions
```sql
pgtle.install_extension_version(
  name text,
  version text,
  description text,
  ext text
)
```

and the `install_update_path` and `set_default_version` functions remain the same.

 ---

but that might be personal preference. What you're working on also sounds good

**Comment by formalLogicGirl** [comment]
Closed by https://github.com/aws/pg_tle/pull/194
