### ISSUE TITLE
Move return statements out of PG_TRY blocks

### ISSUE THREAD

**Issue by formalLogicGirl** [aws/pg_tle#195]
## Description

If we exit a PG_TRY block early via "continue", "break", "goto", or
"return", we'll skip unwinding its exception stack due to the change introduced in [57d0051706] (https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=57d0051706) 

Move return statements out of PG_TRY blocks in all occurrences of this pattern in tleextension.c

**Comment by gurjeet** [comment]
The Postgres commit provided in issue description ([d0aa965c0a](https://git.postgresql.org/gitweb/?p=postgresql.git;a=object;h=d0aa965c0a)) points to fixes in pl/python code. There doesn't seem to be any reference to PG_TRY(), or any related macro, in that commit. Did you intend to link to a different commit!?

**Comment by gurjeet** [comment]
Perhaps this was the intended commit: [57d0051706](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=57d0051706)

**Comment by formalLogicGirl** [comment]
yes, linked the wrong commit, updated
