### ISSUE TITLE
When i Try to install using method 1 i got this error  /usr/bin/flex: No such file or directory

### ISSUE THREAD

**Issue by resulraveendran** [aws/pg_tle#207]
/usr/bin/flex   -o'src/guc-file.c' src/guc-file.l
make: /usr/bin/flex: No such file or directory
make: *** [/usr/lib/postgresql/13/lib/pgxs/src/makefiles/../../src/Makefile.global:760: src/guc-file.c] Error 127

**Comment by jkatz** [comment]
@resulraveendran This error indicates that you need to install [`flex`](https://github.com/westes/flex) on your system. If you're building on a Linux-based system, you'll need to have the PostgreSQL build dependencies installed. Here are some of the packages that you may need:

[https://wiki.postgresql.org/wiki/Compile_and_Install_from_source_code](https://wiki.postgresql.org/wiki/Compile_and_Install_from_source_code)

**Comment by jkatz** [comment]
@resulraveendran As we haven't heard back from you, I'm going to close out this issue. If the above answer did not help solve your problem, please feel free to reopen.
