### ISSUE TITLE
Add cluster-wide support for password check hook

### ISSUE THREAD

**Issue by adamguo0** [aws/pg_tle#229]
## Describe the problem

Currently password check hook functions need to be created and registered in each database that a user might alter passwords on. This can be difficult for admins to manage. We should allow password check functions to be created, registered, and managed from a single database.

## Describe the proposal

password_check_hook currently uses SPI to execute functions stored in the connected database. We can spin up a dynamic background worker to execute functions stored in a different database. Data can be passed between the client process and the background worker via shared memory.

## Describe alternatives

* If this feature is not built, database admins need to write scripts that manage password check functions across databases, which is a hassle.
* Using a background worker and shared memory can be somewhat resource intensive and cumbersome. It also limits parallelization, since each simultaneous background worker needs its own slice of shared memory which must be allocated at postmaster startup.

**Comment by JohnHVancouver** [comment]
I think it's fine if we use the same ConditionVariable scheme you have setup for ClientAuthHook
