### ISSUE TITLE
Support code linting (e.g. plpgsql_check)

### ISSUE THREAD

**Issue by adamflush** [aws/pg_tle#282]
## Ability to Lint Code in Postgres (RDS/Aurora)

* Ability to Lint Code in Postgres (RDS/Aurora)

## Support extensions that permit linting of code

* Support existing extensions or create compatible extensions for the linting of supported and new languages in Postgres, starting of course with PL/pgSQL, which has a great existing extension plpgsql_check.
https://supabase.com/docs/guides/database/extensions/plpgsql_check

## Describe alternatives

* Honestly not sure how to get postgres extensions into AWS approval for use on Postgres RDS or Postgres-compatible Aurora.

**Comment by jim-mlodgenski** [comment]
What would we need to expose in tle to allow a linting function to be written? Likely we'd need to wrap the plpgsql parse in some way, but what else is necessary? plpgsql_check looks pretty extensive, but does a tle function the performs linting need all of the same capabilities? This is a good idea, but a deeper design would be helpful in understanding the scope of this.
